export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';

export const COUNTRY_BYNAME = 'COUNTRY_BYNAME';
export const COUNTRY_BYID = 'COUNTRY_BYID';

export const FILTER = 'FILTER';

export const ORDER_NAME = 'ORDER_NAME';
export const ORDER_CONTINENT = 'ORDER_CONTINENT';
export const ORDER_POPULATION = 'ORDER_POPULATION';
export const ORDER_ACTIVITY = 'ORDER_ACTIVITY';


export const SET_PAGE = 'SET_PAGE';
export const SET_ITEMS_PER_PAGE = 'SET_ITEMS_PER_PAGE'
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';